# Generated by Django 4.2.1 on 2023-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
