# Generated by Django 4.2.1 on 2023-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_trade_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
